### ISSUE TITLE
Configuration of custom cp models

### ISSUE THREAD

**Issue by Justin-Sonneck** [MMV-Lab/mmv-tracking-napari#87]
Idea: Implement the option to configure a custom model, then save the configuration in json

**Comment by lennartkowitz** [comment]
Our own models will be hard coded and not editable.

Custom Cellpose models will be read from JSON file.
JSON structure will be name:{path, diameter, chans: {1, 2}, flow-threshold, cellprob-threshold}
strings: name, path
integers: chan, chan2
floats: diameter, flow-threshold, cellprob-threshold
